---
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'dependencies'
      - 'github_actions'
      - 'go'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'dependencies'
      - 'documentation'
      - 'github_actions'
      - 'go'
  default: patch
exclude-labels:
  - 'skip-changelog'
